= Pourquoi apprendre les Design Patterns ?
Adrien CAUBEL
23/04/2022
:keywords: Design patterns, patrons de conception, apprentissage,
architecture, conception, bonnes patriques

== Pourquoi apprendre les Design Patterns ?

Dans cet article je souhaite plus particulièrement exposer mon ressenti
sur les bénéfices de cet apprentissage; se concentrer plus sur l’aspect
psychologique. Si vous n’êtes pas convaincu de leurs utilités techniques
je vous conseille de lire cet
https://www.oreilly.com/content/5-reasons-to-finally-learn-design-patterns/[article],
sinon je vous laisse continuer de me lire pour comprendre comment ils
m’ont aidé à évoluer dans la conception et le développement
d’applications.

== Une philosophie

Les jours, les mois et les années passent et votre façon de concevoir un
logiciel, de structurer votre code évolue. L’étude des Design Patterns
m’a permis d’accélérer ma compréhension des bonnes pratiques de
conception, de rechercher comment perfectionner la qualité logiciel et
d’aiguiser mon esprit critique par rapport au code que je produis.

Nous sommes amenés à créer du code qui soit viable, flexible et
maintenable facilement. Lorsque vous avez lu, vu, compris l’importance
des Design Patterns et de concevoir un produit de qualité en interne,
vous allez mettre tout en place pour que votre contribution perdure dans
l’application. Lorsque vous allez produire du code, même sans connaitre
tous les Design Patterns vous allez remarquer qu’il y a quelque chose
qui ne va pas. Vous allez réfléchir, questionner Google et trouver une
solution pérenne à votre problème. Cet état d’esprit, cette remise en
question continuelle sur la qualité de mon code je la dois à la lecture,
l’apprentissage des Design Patterns et autres métriques de qualité
logiciel.

À travers ce récit, je veux vous montrer que malgré un apprentissage qui
se veut long, leur étude n’apporte que du positif. En effet, il faut le
voir comme une philosophie qui mature avec les années. Cet apprentissage
vous sera bénéfique pour toute votre carrière de développeur. Le but est
d’évoluer, de gagner en expérience et cela passe par un apprentissage
continu. Et en plus de cela, vous aurez la gratification d’avoir produit
un code de qualité facilement évaluable et maintenable.

Pour ma part, un développeur logiciel ou un développeur qui souhaite
s’orienter dans la conception logicielle en entreprise doit maitriser
les sujets de qualité logiciel. Il semble assez naturel qu’après l’étude
de la programmation-objet, l’étude des Design Patterns soit le prochain
apprentissage à effectuer. Cependant, de nombreux développeurs ne sont
pas allés jusqu’à cette étape. Lorsqu’on ignore l’existence de ces
pratiques, il est compliqué de les mettre en oeuvre naturellement. Et
par transitivité cela peut conduire à un logiciel mal conçu en interne
et demandant un travail monstre pour le faire évoluer et le maintenir.

Je terminerai cet article en revenant sur les premières phrases.
Connaitre les Design Patterns c’est être conscient qu’il faut de la
qualité en interne du logiciel. Connaitre les Design Patterns c’est de
développer un esprit critique, une philosophie, une rigueur qui vous
pousse à produire ce _bon_ code. Connaitre les Design Patterns c’est
remarque qu’il y a un problème dans notre code et de savoir que des
solutions approuvées existent.
